### ISSUE TITLE
statusCode:401 - but no one claims to have added authentication?

### ISSUE THREAD

**Issue by Pharrious** [vjekob/al-objid#25] opened 2022-02-09 14:22 UTC
Hi Vjeko

Today I experienced that one of our extensions suddenly will not communicate with the backup.
All the others in the multiroot workspace are working just fine.
I fear someone might have added authentication 'by accident', but no one says that's the case.
Other developers on the team has the same experience.

`[2022-02-09T13:26:58.642Z] [Verbose] sending request to https://vjekocom-alext-weu.azurewebsites.net/api/v2/getNext: {"appId":"daa37...","type":"tableextension","ranges":[...]}
[2022-02-09T13:26:58.867Z] Sending GET request to /api/v2/getNext endpoint resulted in an error: {"error":"{\n  \"errorMessage\": \"Invalid credentials\"\n}","statusCode":401,"headers":{"transfer-encoding":"chunked","content-type":"text/plain; charset=utf-8","server":"Kestrel","date":"Wed, 09 Feb 2022 13:26:58 GMT","connection":"close"}}`

Is there a way, where we can see what happened?
Running version 2.2.0, last updated 12.12.2021 18.01.22

Thank you

**Comment by Pharrious** [comment] 2022-02-13 18:14
Hi Vjeko

Thank you for the reply, I have send a message on LinkedIn with the whole appid.
Keep up the good work, it is a great and easy tool!

- Martin

**Comment by Bojkas1985** [comment] 2022-02-15 08:49
Hi @vjekob , do you think that could be my problem? Where can I find the application ID? Is it necessary to do this on all the devices involved?

Thank you
Ivica

https://github.com/vjekob/al-objid/issues/24

**Comment by vjekob** [comment] 2022-02-20 06:12
I am closing this issue now:
* It is a duplicate of https://github.com/vjekob/al-objid/issues/15 (read my closing comment if you want to know how the issue is resolved)
* That other issue has just been closed as the solution is being delivered in 2.3.0.

**Closed by vjekob** 2022-02-20 06:12 UTC
